(*
**	Program transformations that eliminate traits
*)

open Types

(* transform_rename
   Renames all expression variables, except the built-in names, to avoid
   conflicts with names generated by the transformations. This renaming only
   prepends a "_" to each name *)
val transform_rename : program -> program

(* transform_imperative
   Removes the imperative traits of the given program while preserving its
   semantics *)
val transform_imperative : program -> program

(* transform_continuation
   Eliminates exceptions by rewriting the program in continuation-style *)
val transform_continuation : program -> program

(* transform
   Repeatedly transform the program by taking transformation name in the list:
   - 'R' eliminates imperative traits
   - 'E' introduces continuations *)
val transform : program -> char list -> program
